spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bookstore?serverTimezone=UTC
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: root
        password: yellowihor32
    jpa:
        hibernate:
            ddl-auto: validate
    show-sql: true
    open-in-view: false
